2011/08/17 02:02:32 [error] [exception.CDbException] could not find driver
2011/08/17 02:02:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(Post))
#7 Y:\home\yii\www\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Post')
#8 Y:\home\yii\www\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 Y:\home\yii\www\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 Y:\home\yii\www\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 Y:\home\yii\www\framework\web\CController.php(1122): CFilter->filter(Object(CFilterChain))
#14 Y:\home\yii\www\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 Y:\home\yii\www\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 Y:\home\yii\www\framework\web\CController.php(283): CFilterChain->run()
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/
2011/08/22 00:41:10 [error] [exception.CDbException] could not find driver
2011/08/22 00:41:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(Post))
#7 Y:\home\yii\www\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Post')
#8 Y:\home\yii\www\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 Y:\home\yii\www\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 Y:\home\yii\www\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 Y:\home\yii\www\framework\web\CController.php(1122): CFilter->filter(Object(CFilterChain))
#14 Y:\home\yii\www\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 Y:\home\yii\www\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 Y:\home\yii\www\framework\web\CController.php(283): CFilterChain->run()
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/
2011/08/22 00:41:25 [error] [exception.CDbException] could not find driver
2011/08/22 00:41:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\framework\web\widgets\CActiveForm.php(745): CModel->validate(NULL)
#14 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(70): CActiveForm::validate(Object(LoginForm))
#15 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#16 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#17 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#18 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#20 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#21 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#22 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#23 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:41:28 [error] [exception.CDbException] could not find driver
2011/08/22 00:41:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\framework\web\widgets\CActiveForm.php(745): CModel->validate(NULL)
#14 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(70): CActiveForm::validate(Object(LoginForm))
#15 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#16 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#17 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#18 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#20 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#21 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#22 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#23 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:41:28 [error] [exception.CDbException] could not find driver
2011/08/22 00:41:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(79): CModel->validate()
#14 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#15 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#16 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:42:16 [error] [exception.CDbException] could not find driver
2011/08/22 00:42:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(79): CModel->validate()
#14 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#15 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#16 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:42:22 [error] [exception.CDbException] could not find driver
2011/08/22 00:42:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(Post))
#7 Y:\home\yii\www\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Post')
#8 Y:\home\yii\www\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 Y:\home\yii\www\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 Y:\home\yii\www\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 Y:\home\yii\www\framework\web\CController.php(1122): CFilter->filter(Object(CFilterChain))
#14 Y:\home\yii\www\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 Y:\home\yii\www\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 Y:\home\yii\www\framework\web\CController.php(283): CFilterChain->run()
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('index')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('post/index')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/post/index
2011/08/22 00:46:38 [error] [exception.CDbException] could not find driver
2011/08/22 00:46:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\framework\web\widgets\CActiveForm.php(745): CModel->validate(NULL)
#14 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(70): CActiveForm::validate(Object(LoginForm))
#15 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#16 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#17 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#18 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#20 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#21 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#22 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#23 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:46:41 [error] [exception.CDbException] could not find driver
2011/08/22 00:46:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(79): CModel->validate()
#14 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#15 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#16 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:46:44 [error] [exception.CDbException] could not find driver
2011/08/22 00:46:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(Post))
#7 Y:\home\yii\www\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Post')
#8 Y:\home\yii\www\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 Y:\home\yii\www\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 Y:\home\yii\www\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 Y:\home\yii\www\framework\web\CController.php(1122): CFilter->filter(Object(CFilterChain))
#14 Y:\home\yii\www\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 Y:\home\yii\www\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 Y:\home\yii\www\framework\web\CController.php(283): CFilterChain->run()
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('index')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('post/index')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/post/index
2011/08/22 00:46:48 [error] [exception.CDbException] could not find driver
2011/08/22 00:46:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(User))
#7 Y:\home\yii\www\demos\blog\protected\models\User.php(21): CActiveRecord::model('User')
#8 Y:\home\yii\www\demos\blog\protected\components\UserIdentity.php(18): User::model()
#9 Y:\home\yii\www\demos\blog\protected\models\LoginForm.php(50): UserIdentity->authenticate()
#10 Y:\home\yii\www\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#11 Y:\home\yii\www\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 Y:\home\yii\www\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#13 Y:\home\yii\www\demos\blog\protected\controllers\SiteController.php(79): CModel->validate()
#14 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#15 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#16 Y:\home\yii\www\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('login')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('site/login')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/index.php/site/login
2011/08/22 00:47:57 [error] [exception.CDbException] could not find driver
2011/08/22 00:47:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in Y:\home\yii\www\framework\db\CDbConnection.php:354
Stack trace:
#0 Y:\home\yii\www\framework\db\CDbConnection.php(297): CDbConnection->open()
#1 Y:\home\yii\www\framework\db\CDbConnection.php(275): CDbConnection->setActive(true)
#2 Y:\home\yii\www\framework\base\CModule.php(372): CDbConnection->init()
#3 Y:\home\yii\www\framework\base\CApplication.php(426): CModule->getComponent('db')
#4 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(607): CApplication->getDb()
#5 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(2236): CActiveRecord->getDbConnection()
#6 Y:\home\yii\www\framework\db\ar\CActiveRecord.php(371): CActiveRecordMetaData->__construct(Object(Post))
#7 Y:\home\yii\www\framework\web\CActiveDataProvider.php(72): CActiveRecord::model('Post')
#8 Y:\home\yii\www\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 Y:\home\yii\www\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 Y:\home\yii\www\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 Y:\home\yii\www\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 Y:\home\yii\www\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 Y:\home\yii\www\framework\web\CController.php(1122): CFilter->filter(Object(CFilterChain))
#14 Y:\home\yii\www\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 Y:\home\yii\www\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 Y:\home\yii\www\framework\web\CController.php(283): CFilterChain->run()
#17 Y:\home\yii\www\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 Y:\home\yii\www\framework\web\CWebApplication.php(328): CController->run('')
#19 Y:\home\yii\www\framework\web\CWebApplication.php(121): CWebApplication->runController('')
#20 Y:\home\yii\www\framework\base\CApplication.php(155): CWebApplication->processRequest()
#21 Y:\home\yii\www\demos\blog\index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/demos/blog/
